sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
build:
  runnerOs: ubuntu-latest
  freeDiskSpace: true
  exasolDbVersions:
    - "8.26.0"
    - "7.1.26"
excludes:
  - "E-PK-CORE-17: Missing required file: 'release_config.yml'"
build:
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: REPLACE
          stepId: build-pk-verify
          content:
            name: Run tests and build with Maven
            id: build-pk-verify
            run: |
              mvn --batch-mode clean verify \
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                  -DtrimStackTrace=false \
                  -Dcom.exasol.dockerdb.image=${{ matrix.exasol_db_version }} \
                  -Pexpensive
