sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_release_on_maven_central.yml'"
build:
  runnerOs: ubuntu-latest
  freeDiskSpace: true
  exasolDbVersions:
    - "8.25.0"
    - "7.1.25"
