sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
build:
  runnerOs: ubuntu-latest
  freeDiskSpace: true
  exasolDbVersions:
    - "8.26.0"
    - "7.1.26"
excludes:
  - "E-PK-CORE-17: Missing required file: 'release_config.yml'"
