sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
build:
  runnerOs: ubuntu-latest
  freeDiskSpace: true
  exasolDbVersions:
    - "8.25.0"
    - "7.1.25"
