language: java

# Setting sudo to false will cause Travis to use Containers.
# To use Docker's privileged mode, we need to enable sudo.
sudo: required

services:
  - docker

env:
  - DOCKER_DB_VERSION=7.0.4
  - DOCKER_DB_VERSION=6.2.12

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration
    verify sonar:sonar
    -Pslow
    -Dsonar.login=${SONAR_TOKEN}
    -Dcom.exasol.docker.image=${DOCKER_DB_VERSION}
    -Djava.util.logging.config.file=src/test/resources/logging.properties

cache:
  directories:
  - $HOME/.m2