# Java is not yet supported on Windows, so the build would block.
# You do not need any setup from Travis, use a plain bash build
language: minimal

sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: exasol

# Enable them all, if you need them.
os:
  - linux
  - windows

env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    #set jdk version
    - JDK="openjdk@1.11.0-2"
  matrix:
    - DOCKER_DB_VERSION=7.0.6
    - DOCKER_DB_VERSION=6.2.13

before_install:
  # Check out the script set
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  # Install the JDK you configured in the $JDK environment variable
  # Never use travis_retry: hides failures. travis_retry is used internally where possible.
  - source $GRAVIS/install-jdk
  # Install the MAVEN_VERSION of your like
  - source $GRAVIS/install-maven
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then
    choco install docker-machine;
    fi
script:
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration
    verify
    -Pslow
    -Dcom.exasol.docker.image=${DOCKER_DB_VERSION}
    -Djava.util.logging.config.file=src/test/resources/logging.properties;
    else
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration
    verify sonar:sonar
    -Pslow
    -Dsonar.login=${SONAR_TOKEN}
    -Dcom.exasol.docker.image=${DOCKER_DB_VERSION}
    -Djava.util.logging.config.file=src/test/resources/logging.properties;
    fi