name: CI Build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        docker_db_version: [7.0.6, 6.2.13]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests and build with Maven
        run: |
          echo
          echo "-------------------------------------------------------------"
          echo "Running matrix test with dockerdb_version $DOCKER_DB_VERSION"
          echo "-------------------------------------------------------------"
          echo
          mvn --batch-mode --update-snapshots clean verify sonar:sonar --file pom.xml \
          -DtrimStackTrace=false -Dsonar.organization=exasol -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN \
          -Pslow \
          -Dcom.exasol.docker.image= \
          -Djava.util.logging.config.file=src/test/resources/logging.properties
        env:
          DOCKER_DB_VERSION: ${{ matrix.docker_db_version }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}